theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "focused_window"
show_marks = "visible"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "CPU {min}"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN", "Package id 0"]

[[block]]
block = "memory"
display_type = "memory"
format_mem = "RAM {mem_used}({mem_used_percents})"
icons = true
interval = 5
warning_mem = 80
critical_mem = 95

[[block]]
block = "memory"
format_swap = "SWAP {swap_used} ({swap_used_percents})"
display_type = "swap"
icons = true
interval = 5
warning_swap = 80
critical_swap = 95

[[block]]
block = "battery"
interval = 5
format = "{percentage}"

[[block]]
block = "net"
device = "wlp1s0"
format = "{ssid} {signal_strength}"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%d/%m %R"
